openapi: "3.1.0"
info:
  title: "Pizza API"
  description: "CRUD API для сущности пиццы"
  version: "1.0.0"
servers:
- url: "http://localhost:8080"

paths:
  /pizza/create:
    post:
      description: "Создание пиццы"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PizzaCreateDto"
        required: true
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PizzaViewDto"

  /pizza/search:
    post:
      description: "Поиск пицц по заданным критериям"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/PizzaViewDto"

  /pizza/getById:
    post:
      description: "Получение пиццы по id"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PizzaViewDto"

  /pizza/update:
    post:
      description: "Обновление данных пиццы"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PizzaUpdateDto"
        required: true
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PizzaViewDto"

  /pizza/delete:
    post:
      description: "Удаление пиццы"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PizzaViewDto"

components:
  schemas:
    BigDecimal:
      type: "object"
      properties: {}

    PizzaViewDto:
      type: "object"
      properties:
        uuid:
          type: "string"
          format: "uuid"
        name:
          type: "string"
        description:
          type: "string"
        weight:
          type: "integer"
          format: "int32"
        price:
          $ref: "#/components/schemas/BigDecimal"
        ingredients:
          type: "array"
          items:
            type: "string"
      required:
      - "uuid"
      - "name"
      - "weight"
      - "price"
      - "ingredients"

    PizzaCreateDto:
      type: "object"
      properties:
        name:
          type: "string"
        description:
          type: "string"
        weight:
          type: "integer"
          format: "int32"
        price:
          $ref: "#/components/schemas/BigDecimal"
        ingredients:
          type: "array"
          items:
            type: "string"
      required:
      - "name"
      - "weight"
      - "price"
      - "ingredients"

    PizzaUpdateDto:
      type: "object"
      properties:
        uuid:
          type: "string"
          format: "uuid"
        name:
          type: "string"
        description:
          type: "string"
        weight:
          type: "integer"
          format: "int32"
        price:
          $ref: "#/components/schemas/BigDecimal"
        ingredients:
          type: "array"
          items:
            type: "string"
      required:
      - "uuid"
      - "name"
      - "weight"
      - "price"
      - "ingredients"
