openapi: 3.1.0
info:
  title: Pizza API
  description: CRUD API для сущности пиццы
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080/api/v1

paths:
  /pizza/create:
    post:
      summary: Создание пиццы
      description: Создание пиццы на основе DTO
      operationId: createPizza
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PizzaCreateRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PizzaViewDto'

  /pizza/read:
    post:
      summary: Получение данных пиццы
      description: Получение данных пиццы по uuid
      operationId: readPizza
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PizzaReadRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PizzaViewDto'

  /pizza/update:
    post:
      summary: Обновление данных пиццы
      description: Обновление данных пиццы по uuid на основе DTO
      operationId: updatePizza
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PizzaUpdateRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PizzaViewDto'

  /pizza/delete:
    post:
      summary: Удаление пиццы
      description: Удаление пиццы по uuid
      operationId: deletePizza
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PizzaDeleteRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PizzaViewDto'

  /pizza/search:
    post:
      summary: Поиск пицц
      description: Поиск пицц по заданным критериям
      operationId: searchPizzas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PizzaSearchRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PizzaViewDto'

components:
  schemas:

    # UUID
    PizzaId:
      type: string
      format: uuid
      description: uuid пиццы

    # Версия оптимистичной блокировки
    Lock:
      type: string
      description: Версия оптимистичной блокировки

    # DTO
    PizzaBaseDto:
      type: object
      description: Общее для всех DTO пиццы
      properties:
        name:
          type: string
          description: Название пиццы
          required: true
        description:
          type: string
          description: Описание пиццы
          required: false
        weight:
          type: integer
          format: int32
          description: Масса пиццы в граммах
          required: true
        price:
          type: number
          format: double
          description: Цена пиццы в рублях
          required: true
        ingredients:
          type: array
          items:
            type: string
          description: Ингридиенты пиццы (кроме теста)
          required: true

    PizzaCreateDto:
      allOf:
        - $ref: '#/components/schemas/PizzaBaseDto'

    PizzaReadDto:
      allOf:
        - type: object
          properties:
            uuid:
              $ref: '#/components/schemas/PizzaId'

    PizzaUpdateDto:
      allOf:
        - type: object
          properties:
            uuid:
              $ref: '#/components/schemas/PizzaId'
        - type: object
          properties:
            lock:
              $ref: '#/components/schemas/Lock'
        - $ref: '#/components/schemas/PizzaBaseDto'

    PizzaDeleteDto:
      allOf:
        - type: object
          properties:
            uuid:
              $ref: '#/components/schemas/PizzaId'
        - type: object
          properties:
            lock:
              $ref: '#/components/schemas/Lock'

    PizzaViewDto:
      allOf:
        - type: object
          properties:
            uuid:
              $ref: '#/components/schemas/PizzaId'
        - $ref: '#/components/schemas/PizzaBaseDto'

    PizzaSearchFilter:
      type: object
      description: Критерии фильтрации для поиска пицц
      properties:
        nameContains:
          type: string
          description: Название пиццы должно содержать
          required: false
        descriptionContains:
          type: string
          description: Описание пиццы должно содержать
          required: false
        weightFrom:
          type: integer
          description: Масса пиццы не менее
          required: false
        weightTo:
          type: integer
          description: Масса пиццы не более
          required: false
        priceFrom:
          type: number
          format: double
          description: Цена пиццы не менее
          required: false
        priceTo:
          type: number
          format: double
          description: Цена пиццы не более
          required: false
        pizzaContains:
          type: array
          items:
            type: string
          description: Ингридиенты пиццы должны содержать
          required: false

    # Requests
    IRequest:
      type: object
      description: Базовый интерфейс для всех запросов
      properties:
        requestType:
          type: string
          description: Поле-дескриминатор для вычисления типа запроса
          example: create
          required: true
      discriminator:
        propertyName: requestType
        mapping:
          create: '#/components/schemas/PizzaCreateRequest'
          read: '#/components/schemas/PizzaReadRequest'
          update: '#/components/schemas/PizzaUpdateRequest'
          delete: '#/components/schemas/PizzaDeleteRequest'
          search: '#/components/schemas/PizzaSearchRequest'

    PizzaCreateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            pizza:
              $ref: '#/components/schemas/PizzaCreateDto'

    PizzaReadRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            pizza:
              $ref: '#/components/schemas/PizzaReadDto'

    PizzaUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            pizza:
              $ref: '#/components/schemas/PizzaUpdateDto'

    PizzaDeleteRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            pizza:
              $ref: '#/components/schemas/PizzaDeleteDto'

    PizzaSearchRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            filter:
              $ref: '#/components/schemas/PizzaSearchFilter'
