openapi: "3.1.0"
info:
  title: "Pizza API"
  description: "fast-pizza pizza API"
  version: "1.0.0"
servers:
- url: "http://localhost:8083"
paths:
  /pizza:
    get:
      description: "Find all pizzas"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/PizzaViewDto"
    post:
      description: "Create pizza"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PizzaCreateDto"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PizzaViewDto"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                type: "string"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                type: "string"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                type: "string"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                type: "string"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                type: "string"
  /pizza/{id}:
    get:
      description: "Find pizza by id"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PizzaViewDto"
    put:
      description: "Update pizza"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PizzaUpdateDto"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PizzaViewDto"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                type: "string"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                type: "string"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                type: "string"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                type: "string"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                type: "string"
    delete:
      description: "Delete pizza by id"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "204":
          description: "No Content"

components:
  schemas:
    BigDecimal:
      type: "object"
      properties: {}
    PizzaViewDto:
      type: "object"
      properties:
        uuid:
          type: "string"
          format: "uuid"
        name:
          type: "string"
        description:
          type: "string"
        weight:
          type: "integer"
          format: "int32"
        price:
          $ref: "#/components/schemas/BigDecimal"
        ingredients:
          type: "array"
          items:
            type: "string"
      required:
      - "uuid"
      - "name"
      - "weight"
      - "price"
      - "ingredients"
    PizzaCreateDto:
      type: "object"
      properties:
        name:
          type: "string"
        description:
          type: "string"
        weight:
          type: "integer"
          format: "int32"
        price:
          $ref: "#/components/schemas/BigDecimal"
        ingredients:
          type: "array"
          items:
            type: "string"
      required:
      - "name"
      - "weight"
      - "price"
      - "ingredients"
    PizzaUpdateDto:
      type: "object"
      properties:
        uuid:
          type: "string"
          format: "uuid"
        description:
          type: "string"
        weight:
          type: "integer"
          format: "int32"
        price:
          $ref: "#/components/schemas/BigDecimal"
        ingredients:
          type: "array"
          items:
            type: "string"
      required:
      - "uuid"
      - "weight"
      - "price"
      - "ingredients"